### ISSUE TITLE
we need more app files

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/stress-app#2]
we need something that mimics what a realistic (but aimed at larger 100,000 -> 200,000loc apps) app will have in terms of

* dirs
* templates
* js files
* sass
* tests
* public assets

–––

All the apps i work on, are not open source, so simply harvesting the files is not an options. Maybe we can track down some open source projects and use them as a starting point.

**Comment by locks** [comment]
You can steal from mine: https://github.com/fzerocentral/next.
What about known OSS codebases like Travis and Discourse?

**Comment by stefanpenner** [comment]
> What about known OSS codebases like Travis and Discourse?

Ya I was thinking about those. If there license is reasonable, i would love to doit.

**Comment by rtablada** [comment]
@stefanpenner currently working on a OSS hackathon project. I can PR that in.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/stress-app/pull/5 solves this for now.

**Comment by tschoartschi** [comment]
@stefanpenner I could submit a demo of our "Unity WebGL export" so you can investigate issue #4055 (https://github.com/ember-cli/ember-cli/issues/4055)

I can't provide our original code because it's not open source and still under development but the demo could demonstrate the issue perfectly.

**Comment by stefanpenner** [comment]
@tschoartschi yes that would be great

**Comment by tschoartschi** [comment]
How should I submit the files? Is a PR the right way?

**Comment by stefanpenner** [comment]
Yup

**Comment by tschoartschi** [comment]
Tried to create a pull request. It's my first pull request, hope it is ok.
